[pack]
longName = 'My datapack'
name = 'datapack'
description = 'My compiled datapack'
namespace = 'pack'
icon = 'minecraft:chest'

[author]
name = 'Silas Pockendahl'
player = 'B4liz0ng'

[compilation]
sourceDir = './src'
emitDir = './'
minimumVersion = '0.1.0'
obscureNames = false
noInference = false
noImplicitCast = true
ignoreUnreachable = true
sourceMap = true
optimize = true
noUnused = false
ignoreWarnings = false
verbosity = 3
colorLog = true
targetVersion = 'latest'
debugBuild = true
