[pack]
longName = "My datapack"
name = "datapack"
description = "No description available"
namespace = "pack"
version = "0.1.0"

[author]
name = "Unknown author"

[convention]
generate = true
icon = "minecraft:chest"
player = "B4liz0ng"

[compilation]
sourceDir = "./src"
emitDir = "./"
minimumVersion = "0.1.0"
obscureNames = false
noInference = true
noImplicitCast = true
ignoreUnreachable = true
sourceMap = true
optimize = false
noUnused = false
targetVersion = "latest"
debugBuild = true
